= Nayouchi

What sounds Japanese is short for Name Your Child!

== Prerequisites

* Apache Maven
* JDK 8+
* node, npm

== Getting started

Create your project with:

[source]
----
git clone https://github.com/abulvenz/nayouchi
----

== Running the project

Once you have retrieved the project, you can check that everything works with:

[source]
----
mvn test exec:java
----

The command compiles the project and runs the tests, then  it launches the application, so you can check by yourself. Open your browser to http://localhost:8080. You should see a working mithril application.

== Anatomy of the project

The project contains:

* a `pom.xml` file
* a _main_ verticle file (src/main/java/io/vertx/starter/MainVerticle.java)
* an unit test (src/main/test/io/vertx/starter/MainVerticleTest.java)

== Start to hack

Run 

----
npm start
----

in one terminal and in another

----
./redeploy.sh
----

NOTE: the `redeploy` script are also configurable

== Building the project

To build the project, just use:

----
mvn clean package
----

It generates a _fat-jar_ in the `target` directory.
